version: '3'
services:

  mysql:
        container_name: mysql

        env_file:
        - .env
        
        image: mariadb:latest

        command: --max_allowed_packet=256M
        
        volumes:
          - "./data/db:/var/lib/mysql:delegated"

        expose:
          - "3306"

        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          TZ: ${TimeZone}

        restart: always

        networks:
          - unit
      
  phpmyadmin:
    container_name: phpmyadmin

    image: phpmyadmin:latest

    ports:
      - 8080:80

    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=100M
    depends_on:
      - mysql
      
    restart: always

    networks:
      - unit

networks:
  unit:
    external: true

